repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: script-must-not-have-extension
        name: executable shell scripts extensions are removed
      - id: shellcheck
        name: check for linting errors in shell files
      - id: shfmt
        name: check for formatting issues in shell files
        args: ["-i", "2", "-ci", "-bn", "-d"]
