version: "3"

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - type: bind
        source: ~/.config/heimdall
        target: /config
    ports:
      - target: 80
        published: 80
      - target: 443
        published: 443
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      # - USER=jarmos
      # - PASS=jarmos@4991
    ports:
      - target: 9091
        published: 9091
      - target: 51413
        published: 51413
      - target: 51413
        published: 51413
        protocol: udp
    volumes:
      - type: bind
        source: ~/downloads
        target: /downloads
      - type: bind
        source: ~/downloads/torrents
        target: /watch
      - type: bind
        source: ~/.config/transmission
        target: /config
    restart: unless-stopped
