#!/usr/bin/env python3

"""Script to automate my personal homelab server setup."""


def main() -> None:
    """Entrypoint of the script."""
    print("Hello World!")


if __name__ == "__main__":
    main()
