---
# Ensure the "jarmos" group is added to the homelab
- name: Ensure Required User Groups Exist
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ common_sudo_group }}"
    append: true
  tags: [common]

# Ensure the "jarmos" user has sudo access
- name: Configure passwordless sudo access
  tags: [common]
  block:
    - name: Ensure Sudoers Directory Exists
      ansible.builtin.file:
        path: "{{ common_sudoers_directory }}"
        state: directory
        owner: root
        group: root
        mode: "0750"

    - name: Grant Passwordless sudo Access to User
      ansible.builtin.template:
        src: sudoers.j2
        dest: "{{ common_sudoers_directory }}/{{ ansible_user }}"
        owner: root
        group: root
        mode: "0440"
        validate: "/usr/sbin/visudo --check --file=%s"

# Install some necessary packages for maintaining the homelab
- name: Install Required Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ common_packages }}"
  tags: [common]

# Ensure the "pmlogger" service is enabled and started since it is necessary for
# tracking various metrics of the server (like CPU usage and so on)
- name: Start and Enable the pmlogger Service
  ansible.builtin.systemd:
    name: pmlogger.service
    state: started
    enabled: true
  notify: Restart pmlogger
  tags: [common]

# Ensure the SDK for managing Docker using Ansible is available on the server
- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop: "{{ common_docker_sdk }}"
  tags: [common]
