---
- name: Ensure Required User Groups Exist
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ common_sudo_group }}"
    append: true

- name: Ensure Sudoers Directory Exists
  ansible.builtin.file:
    path: "{{ common_sudoers_directory }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Grant Passwordless sudo Access to User
  ansible.builtin.template:
    src: sudoers.j2
    dest: "{{ common_sudoers_directory }}/{{ ansible_user }}"
    owner: root
    group: root
    mode: "0440"
    validate: "/usr/sbin/visudo --check --file=%s"

- name: Install Required Packages
  ansible.builtin.dnf5:
    name: "{{ common_packages }}"
    state: latest

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: "{{ common_docker_sdk }}"
    state: present
