---
- name: Setup Tranmission
  community.docker.docker_container:
    name: transmission
    image: lscr.io/linuxserver/transmission:latest
    restart_policy: unless-stopped
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - "{{ transmission_config_dir }}:/config"
      - "{{ transmission_downloads_dir }}:/downloads"
      - "{{ transmission_watch_dir }}:/watch"
    env:
      PUID: "{{ ansible_user_uid | string }}"
      PGID: "{{ ansible_user_gid | string }}"
      TZ: "{{ transmission_timezone | string }}"
