---
- name: Ensure Homepage Config Directory Exists
  ansible.builtin.file:
    path: "{{ homepage_config_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: Deploy Homepage Configuration Files
  ansible.builtin.template:
    src: templates/{{ item }}
    dest: "{{ homepage_config_dir }}/{{ item | regex_replace('.j2$', '') }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
  loop:
    - settings.yaml.j2
    - bookmarks.yaml.j2
    - widgets.yaml.j2

- name: Deploy Homepage Container
  community.docker.docker_container:
    name: homepage
    image: "{{ homepage_image }}"
    restart_policy: unless-stopped
    recreate: true
    pull: true
    ports:
      - "3000:3000"
    volumes:
      - "{{ homepage_config_dir }}:/config"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      PUID: "{{ ansible_user_uid | default(1000) }}"
      PGID: "{{ ansible_user_gid | default(1000) }}"
      HOMEPAGE_ALLOWED_HOSTS: "{{ homepage_allowed_hosts }}"
