---
- name: Build and install cockpit-files
  block:
    - name: Build "cockpit-files"
      environment:
        NODE_ENV: production
      community.general.make:
        chdir: "{{ cockpit_local_repo }}"

    - name: Install 'cockpit-files'
      community.general.make:
        chdir: "{{ cockpit_local_repo }}"
        target: install
      args:
        creates: "{{ cockpit_install_dir }}"
