---
- name: Fetch the Dotfiles Repository
  ansible.builtin.git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ dotfiles_dest }}"
    version: "{{ dotfiles_version }}"
    update: true
    force: false

- name: Ensure Proper Ownership and Permissions for Dotfiles
  ansible.builtin.file:
    path: "{{ dotfiles_dest }}"
    state: directory
    owner: "{{ dotfiles_owner }}"
    group: "{{ dotfiles_group }}"
    mode: "0755"
