---
- name: Add Docker's Official Repository
  ansible.builtin.get_url:
    url: "{{ docker_repo_url }}"
    dest: "{{ docker_repo_dest }}"
    mode: "0644"

- name: Install Docker Packages
  ansible.builtin.dnf:
    name: "{{ docker_packages }}"
    state: present

- name: Start and Enable Docker Service
  ansible.builtin.systemd:
    name: "{{ docker_service_name }}"
    state: started
    enabled: true

- name: Add User to the Docker Group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "{{ docker_group }}"
    append: true
  notify: Reset connection
