---
- name: Perform Homelab Maintenance
  hosts: homelab
  user: jarmos
  become: true

  tasks:
    - name: Update Installed Packages
      ansible.builtin.dnf5:
        name: "*"
        state: latest

    - name: Restart Docker Service
      ansible.builtin.systemd:
        name: docker
        state: started

    - name: Clean Up Unused Docker Resources
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true

    - name: Update the Dotfiles
      ansible.builtin.git:
        repo: https://github.com/Jarmos-san/dotfiles.git
        dest: /home/{{ ansible_user }}/.dotfiles
        update: true
        version: main
