---
- name: Configure the Homelab
  hosts: homelab
  user: jarmos
  become: true

  pre_tasks:
    - name: Update the Sytem
      ansible.builtin.dnf5:
        name: "*"
        state: latest

  roles:
    - common
    - dotfiles
    - docker
