---
- name: Configure the Homelab
  hosts: homelab
  user: jarmos
  become: true

  pre_tasks:
    - name: Update the Sytem
      ansible.builtin.dnf5:
        name: "*"
        state: latest

  tasks:
    - name: Ensure the "jarmos" User is in the "wheel" Group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: wheel
        append: true

    - name: Ensure "/etc/sudoers.d/" Directory Exists
      ansible.builtin.file:
        path: /etc/sudoers.d
        state: directory
        owner: root
        group: root
        mode: "0750"

    - name: Allow the "jarmos" User to Use sudo Without Password
      ansible.builtin.copy:
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL\n"
        owner: root
        group: root
        mode: "0440"
        validate: "/usr/sbin/visudo --check --file=%s"

    - name: Install Necessary Software
      ansible.builtin.dnf5:
        name: ["git", "curl", "make", "tmux", "neovim", "nodejs"]

    - name: Fetch the Dotfiles
      ansible.builtin.git:
        repo: https://github.com/Jarmos-san/dotfiles.git
        dest: /home/{{ ansible_user }}/.dotfiles
        version: main

    - name: Assign the Dotfiles Directory to the "jarmos" User
      ansible.builtin.file:
        path: /home/{{ ansible_user }}/.dotfiles
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Ping Server
      ansible.builtin.ping:
