name: QA Checks

on:
  push:
    branches-ignore:
      - "dependabot/**"

permissions:
  contents: read

jobs:
  qa-checks:
    name: QA Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install `ansible-lint`
        run: pip install ansible-lint

      - name: Lint Ansible Files
        run: ansible-lint ./ansible
