name: QA Checks

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  qa-checks:
    name: QA Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.0.0

      - name: Install Poetry
        run: |
          export POETRY_HOME=/opt/poetry
          curl --fail --silent --show-error --location \
            https://install.python-poetry.org | python3 -
          export PATH="/opt/poetry/bin:$PATH"

      - name: Setup Python for the Environment
        uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.11"
          cache: poetry

      - name: Install the Development Dependencies
        run: poetry install --no-root --only=dev

      - name: Run Type Checking
        run: poetry run mypy setup

      - name: Run Formatting Checks
        run: poetry run black setup --check

      - name: Run Linting Checks
        run: poetry run ruff check setup
