name: QA Checks

on:
  push:
    branches-ignore:
      - "dependabot/**"

permissions:
  contents: read

jobs:
  qa-checks:
    name: QA Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Install `ansible` & `ansible-lint`
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Install Ansible Collections
        working-directory: ansible
        run:
          ansible-galaxy collection install --requirements-file requirements.yml

      - name: Lint Ansible Files
        run: ansible-lint ./ansible
