name: QA Checks

on:
  push:
    branches-ignore:
      - "dependabot/**"

permissions:
  contents: read

jobs:
  qa-checks:
    name: QA Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Ansible Collections
        uses: actions/cache@v4.2.2
        with:
          path: ~/.ansible/collections
          key: ansible-collections-${{ hashFiles('ansible/requirements.yml') }}

      - name: Cache Python Dependencies
        uses: actions/cache@v4.2.2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install `ansible` & `ansible-lint`
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run `ansible-lint`
        run: |
          ansible-lint ./ansible
