name: QA Checks

on:
  push:
    branches-ignore:
      - "dependabot/**"

jobs:
  qa-checks:
    name: QA Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Setup Python for the Environment
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"

      - name: Download and Setup Shfmt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo mvdan/sh --pattern "shfmt_v3.7.0_linux_amd64"
          cp  "shfmt_v3.7.0_linux_amd64" "/usr/local/bin/shfmt"

      - name: Setup Pre-Commit for QA Checks
        uses: pre-commit/action@v3.0.1
